# colorscheme plugins

[[plugins]]
repo = 'cocopon/iceberg.vim'
merged = 0

[[plugins]] 
repo = 'jdkanani/vim-material-theme'
merged = 0

[[plugins]] 
repo = 'sonph/onehalf'
rtp = 'vim'
merged = 0

[[plugins]] 
repo = 'ciaranm/inkpot'
merged = 0

[[plugins]] 
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_source = '''   
  set laststatus=2

  let g:airline_experimental = 1
  let g:airline_detect_spell=1
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#virtualenv#enabled = 1

  if !exists('g:airline_symbols')
      let g:airline_symbols = {}
  endif

  " airline symbols
  let g:airline_left_sep = 'î‚°'
  let g:airline_left_alt_sep = 'î‚±'
  let g:airline_right_sep = 'î‚²'
  let g:airline_right_alt_sep = 'î‚³'
  let g:airline_symbols.linenr = ' î‚¡:'
  let g:airline_symbols.maxlinenr = 'â˜° '
  let g:airline_symbols.dirty='âš¡'
  let g:airline_symbols.paste = 'Ï'
  let g:airline_symbols.branch = 'î‚ '
  let g:airline_symbols.readonly = 'î‚¢'
  let g:airline_symbols.colnr = ' â„…:'
  let g:airline_symbols.crypt = 'ğŸ”’'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

